// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package eBPFListeners

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfFileEvent struct {
	_          structs.HostLayout
	Type       uint32
	Pid        uint32
	Uid        uint32
	Gid        uint32
	Comm       [16]int8
	Filename   [256]int8
	TargetPath [256]int8
	Mode       uint32
	Flags      uint32
	Timestamp  uint64
	Size       uint64
	Ret        int64
}

type bpfMmapEvent struct {
	_         structs.HostLayout
	Type      uint32
	Pid       uint32
	Uid       uint32
	Comm      [16]int8
	_         [4]byte
	Addr      uint64
	Length    uint64
	Prot      uint32
	Flags     uint32
	Fd        int32
	Filename  [256]int8
	_         [4]byte
	Timestamp uint64
}

type bpfModuleEvent struct {
	_         structs.HostLayout
	Type      uint32
	Pid       uint32
	Uid       uint32
	Gid       uint32
	Comm      [16]int8
	Name      [256]int8
	Timestamp uint64
	Ret       int64
}

type bpfNetworkEvent struct {
	_         structs.HostLayout
	Type      uint32
	Pid       uint32
	Uid       uint32
	Gid       uint32
	Comm      [16]int8
	SrcAddr   [16]uint8
	DstAddr   [16]uint8
	SrcPort   uint16
	DstPort   uint16
	Protocol  uint8
	Family    uint8
	_         [2]byte
	Timestamp uint64
	Ret       int64
}

type bpfProcessEvent struct {
	_         structs.HostLayout
	Type      uint32
	Pid       uint32
	Ppid      uint32
	Uid       uint32
	Gid       uint32
	Euid      uint32
	Egid      uint32
	Comm      [16]int8
	Filename  [256]int8
	Args      [512]int8
	Cwd       [256]int8
	_         [4]byte
	Timestamp uint64
	Ret       int64
}

type bpfPtraceEvent struct {
	_         structs.HostLayout
	Type      uint32
	Pid       uint32
	TargetPid uint32
	Uid       uint32
	Comm      [16]int8
	Request   uint32
	_         [4]byte
	Timestamp uint64
	Ret       int64
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	TraceAccept       *ebpf.ProgramSpec `ebpf:"trace_accept"`
	TraceBind         *ebpf.ProgramSpec `ebpf:"trace_bind"`
	TraceBpf          *ebpf.ProgramSpec `ebpf:"trace_bpf"`
	TraceClone        *ebpf.ProgramSpec `ebpf:"trace_clone"`
	TraceConnect      *ebpf.ProgramSpec `ebpf:"trace_connect"`
	TraceDeleteModule *ebpf.ProgramSpec `ebpf:"trace_delete_module"`
	TraceExecve       *ebpf.ProgramSpec `ebpf:"trace_execve"`
	TraceExitGroup    *ebpf.ProgramSpec `ebpf:"trace_exit_group"`
	TraceFchmodat     *ebpf.ProgramSpec `ebpf:"trace_fchmodat"`
	TraceFchownat     *ebpf.ProgramSpec `ebpf:"trace_fchownat"`
	TraceInitModule   *ebpf.ProgramSpec `ebpf:"trace_init_module"`
	TraceLinkat       *ebpf.ProgramSpec `ebpf:"trace_linkat"`
	TraceListen       *ebpf.ProgramSpec `ebpf:"trace_listen"`
	TraceMemfdCreate  *ebpf.ProgramSpec `ebpf:"trace_memfd_create"`
	TraceMmap         *ebpf.ProgramSpec `ebpf:"trace_mmap"`
	TraceMprotect     *ebpf.ProgramSpec `ebpf:"trace_mprotect"`
	TraceOpenat       *ebpf.ProgramSpec `ebpf:"trace_openat"`
	TracePrctl        *ebpf.ProgramSpec `ebpf:"trace_prctl"`
	TracePtrace       *ebpf.ProgramSpec `ebpf:"trace_ptrace"`
	TraceRecvmsg      *ebpf.ProgramSpec `ebpf:"trace_recvmsg"`
	TraceRemovexattr  *ebpf.ProgramSpec `ebpf:"trace_removexattr"`
	TraceRenameat2    *ebpf.ProgramSpec `ebpf:"trace_renameat2"`
	TraceSendmsg      *ebpf.ProgramSpec `ebpf:"trace_sendmsg"`
	TraceSetgid       *ebpf.ProgramSpec `ebpf:"trace_setgid"`
	TraceSetuid       *ebpf.ProgramSpec `ebpf:"trace_setuid"`
	TraceSetxattr     *ebpf.ProgramSpec `ebpf:"trace_setxattr"`
	TraceSymlinkat    *ebpf.ProgramSpec `ebpf:"trace_symlinkat"`
	TraceTruncate     *ebpf.ProgramSpec `ebpf:"trace_truncate"`
	TraceUnlinkat     *ebpf.ProgramSpec `ebpf:"trace_unlinkat"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	Events      *ebpf.MapSpec `ebpf:"events"`
	FileHeap    *ebpf.MapSpec `ebpf:"file_heap"`
	MmapHeap    *ebpf.MapSpec `ebpf:"mmap_heap"`
	ModuleHeap  *ebpf.MapSpec `ebpf:"module_heap"`
	NetworkHeap *ebpf.MapSpec `ebpf:"network_heap"`
	ProcessHeap *ebpf.MapSpec `ebpf:"process_heap"`
	PtraceHeap  *ebpf.MapSpec `ebpf:"ptrace_heap"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	Events      *ebpf.Map `ebpf:"events"`
	FileHeap    *ebpf.Map `ebpf:"file_heap"`
	MmapHeap    *ebpf.Map `ebpf:"mmap_heap"`
	ModuleHeap  *ebpf.Map `ebpf:"module_heap"`
	NetworkHeap *ebpf.Map `ebpf:"network_heap"`
	ProcessHeap *ebpf.Map `ebpf:"process_heap"`
	PtraceHeap  *ebpf.Map `ebpf:"ptrace_heap"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.Events,
		m.FileHeap,
		m.MmapHeap,
		m.ModuleHeap,
		m.NetworkHeap,
		m.ProcessHeap,
		m.PtraceHeap,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	TraceAccept       *ebpf.Program `ebpf:"trace_accept"`
	TraceBind         *ebpf.Program `ebpf:"trace_bind"`
	TraceBpf          *ebpf.Program `ebpf:"trace_bpf"`
	TraceClone        *ebpf.Program `ebpf:"trace_clone"`
	TraceConnect      *ebpf.Program `ebpf:"trace_connect"`
	TraceDeleteModule *ebpf.Program `ebpf:"trace_delete_module"`
	TraceExecve       *ebpf.Program `ebpf:"trace_execve"`
	TraceExitGroup    *ebpf.Program `ebpf:"trace_exit_group"`
	TraceFchmodat     *ebpf.Program `ebpf:"trace_fchmodat"`
	TraceFchownat     *ebpf.Program `ebpf:"trace_fchownat"`
	TraceInitModule   *ebpf.Program `ebpf:"trace_init_module"`
	TraceLinkat       *ebpf.Program `ebpf:"trace_linkat"`
	TraceListen       *ebpf.Program `ebpf:"trace_listen"`
	TraceMemfdCreate  *ebpf.Program `ebpf:"trace_memfd_create"`
	TraceMmap         *ebpf.Program `ebpf:"trace_mmap"`
	TraceMprotect     *ebpf.Program `ebpf:"trace_mprotect"`
	TraceOpenat       *ebpf.Program `ebpf:"trace_openat"`
	TracePrctl        *ebpf.Program `ebpf:"trace_prctl"`
	TracePtrace       *ebpf.Program `ebpf:"trace_ptrace"`
	TraceRecvmsg      *ebpf.Program `ebpf:"trace_recvmsg"`
	TraceRemovexattr  *ebpf.Program `ebpf:"trace_removexattr"`
	TraceRenameat2    *ebpf.Program `ebpf:"trace_renameat2"`
	TraceSendmsg      *ebpf.Program `ebpf:"trace_sendmsg"`
	TraceSetgid       *ebpf.Program `ebpf:"trace_setgid"`
	TraceSetuid       *ebpf.Program `ebpf:"trace_setuid"`
	TraceSetxattr     *ebpf.Program `ebpf:"trace_setxattr"`
	TraceSymlinkat    *ebpf.Program `ebpf:"trace_symlinkat"`
	TraceTruncate     *ebpf.Program `ebpf:"trace_truncate"`
	TraceUnlinkat     *ebpf.Program `ebpf:"trace_unlinkat"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.TraceAccept,
		p.TraceBind,
		p.TraceBpf,
		p.TraceClone,
		p.TraceConnect,
		p.TraceDeleteModule,
		p.TraceExecve,
		p.TraceExitGroup,
		p.TraceFchmodat,
		p.TraceFchownat,
		p.TraceInitModule,
		p.TraceLinkat,
		p.TraceListen,
		p.TraceMemfdCreate,
		p.TraceMmap,
		p.TraceMprotect,
		p.TraceOpenat,
		p.TracePrctl,
		p.TracePtrace,
		p.TraceRecvmsg,
		p.TraceRemovexattr,
		p.TraceRenameat2,
		p.TraceSendmsg,
		p.TraceSetgid,
		p.TraceSetuid,
		p.TraceSetxattr,
		p.TraceSymlinkat,
		p.TraceTruncate,
		p.TraceUnlinkat,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_arm64_bpfel.o
var _BpfBytes []byte
