// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfCapsetEvent struct {
	_           structs.HostLayout
	Type        uint32
	Pid         uint32
	Uid         uint32
	Comm        [16]int8
	Pad0        uint32
	Effective   uint64
	Permitted   uint64
	Inheritable uint64
	Timestamp   uint64
	Ret         int64
}

type bpfDnsEventRaw struct {
	_          structs.HostLayout
	Type       uint32
	Pid        uint32
	Timestamp  uint64
	Comm       [16]int8
	Uid        uint32
	PayloadLen uint32
	Payload    [256]int8
}

type bpfFileEvent struct {
	_          structs.HostLayout
	Type       uint32
	Pid        uint32
	Uid        uint32
	Gid        uint32
	Comm       [16]int8
	Filename   [256]int8
	TargetPath [256]int8
	Mode       uint32
	Flags      uint32
	Timestamp  uint64
	Size       uint64
	Ret        int64
}

type bpfMmapEvent struct {
	_         structs.HostLayout
	Type      uint32
	Pid       uint32
	Uid       uint32
	Comm      [16]int8
	Pad0      uint32
	Addr      uint64
	Length    uint64
	Prot      uint32
	MapFlags  uint32
	Fd        int32
	Pad1      uint32
	Filename  [256]int8
	Timestamp uint64
}

type bpfModuleEvent struct {
	_         structs.HostLayout
	Type      uint32
	Pid       uint32
	Uid       uint32
	Gid       uint32
	Comm      [16]int8
	Name      [256]int8
	Timestamp uint64
	Ret       int64
}

type bpfNamespaceEvent struct {
	_         structs.HostLayout
	Type      uint32
	Pid       uint32
	Uid       uint32
	Comm      [16]int8
	NsType    uint32
	Flags     uint32
	_         [4]byte
	Timestamp uint64
	Ret       int64
}

type bpfNetworkEvent struct {
	_         structs.HostLayout
	Type      uint32
	Pid       uint32
	Uid       uint32
	Gid       uint32
	Comm      [16]int8
	SrcAddr   [16]uint8
	DstAddr   [16]uint8
	SrcPort   uint16
	DstPort   uint16
	Protocol  uint8
	Family    uint8
	Pad0      [2]uint8
	Timestamp uint64
	Ret       int64
}

type bpfProcessEvent struct {
	_         structs.HostLayout
	Type      uint32
	Pid       uint32
	Ppid      uint32
	Uid       uint32
	Gid       uint32
	Euid      uint32
	Egid      uint32
	Comm      [16]int8
	Filename  [256]int8
	Args      [512]int8
	Cwd       [256]int8
	Pad0      uint32
	Flags     uint32
	_         [4]byte
	Timestamp uint64
	Ret       int64
}

type bpfPtraceEvent struct {
	_         structs.HostLayout
	Type      uint32
	Pid       uint32
	TargetPid uint32
	Uid       uint32
	Comm      [16]int8
	Request   uint32
	Pad0      uint32
	Timestamp uint64
	Ret       int64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	bpfMapCapsetHeap        = "capset_heap"
	bpfMapDnsHeap           = "dns_heap"
	bpfMapEvents            = "events"
	bpfMapFileHeap          = "file_heap"
	bpfMapMmapHeap          = "mmap_heap"
	bpfMapModuleHeap        = "module_heap"
	bpfMapNamespaceHeap     = "namespace_heap"
	bpfMapNetworkHeap       = "network_heap"
	bpfMapProcessHeap       = "process_heap"
	bpfMapPtraceHeap        = "ptrace_heap"
	bpfProgTraceBind        = "trace_bind"
	bpfProgTraceCapset      = "trace_capset"
	bpfProgTraceConnect     = "trace_connect"
	bpfProgTraceExecve      = "trace_execve"
	bpfProgTraceFchmodat    = "trace_fchmodat"
	bpfProgTraceFinitModule = "trace_finit_module"
	bpfProgTraceInitModule  = "trace_init_module"
	bpfProgTraceMemfdCreate = "trace_memfd_create"
	bpfProgTraceMmap        = "trace_mmap"
	bpfProgTraceMprotect    = "trace_mprotect"
	bpfProgTraceOpenat      = "trace_openat"
	bpfProgTracePtrace      = "trace_ptrace"
	bpfProgTraceRenameat2   = "trace_renameat2"
	bpfProgTraceSendmsg     = "trace_sendmsg"
	bpfProgTraceSendto      = "trace_sendto"
	bpfProgTraceSetgid      = "trace_setgid"
	bpfProgTraceSetns       = "trace_setns"
	bpfProgTraceSetuid      = "trace_setuid"
	bpfProgTraceSocket      = "trace_socket"
	bpfProgTraceUnlinkat    = "trace_unlinkat"
	bpfProgTraceUnshare     = "trace_unshare"
)

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	TraceBind        *ebpf.ProgramSpec `ebpf:"trace_bind"`
	TraceCapset      *ebpf.ProgramSpec `ebpf:"trace_capset"`
	TraceConnect     *ebpf.ProgramSpec `ebpf:"trace_connect"`
	TraceExecve      *ebpf.ProgramSpec `ebpf:"trace_execve"`
	TraceFchmodat    *ebpf.ProgramSpec `ebpf:"trace_fchmodat"`
	TraceFinitModule *ebpf.ProgramSpec `ebpf:"trace_finit_module"`
	TraceInitModule  *ebpf.ProgramSpec `ebpf:"trace_init_module"`
	TraceMemfdCreate *ebpf.ProgramSpec `ebpf:"trace_memfd_create"`
	TraceMmap        *ebpf.ProgramSpec `ebpf:"trace_mmap"`
	TraceMprotect    *ebpf.ProgramSpec `ebpf:"trace_mprotect"`
	TraceOpenat      *ebpf.ProgramSpec `ebpf:"trace_openat"`
	TracePtrace      *ebpf.ProgramSpec `ebpf:"trace_ptrace"`
	TraceRenameat2   *ebpf.ProgramSpec `ebpf:"trace_renameat2"`
	TraceSendmsg     *ebpf.ProgramSpec `ebpf:"trace_sendmsg"`
	TraceSendto      *ebpf.ProgramSpec `ebpf:"trace_sendto"`
	TraceSetgid      *ebpf.ProgramSpec `ebpf:"trace_setgid"`
	TraceSetns       *ebpf.ProgramSpec `ebpf:"trace_setns"`
	TraceSetuid      *ebpf.ProgramSpec `ebpf:"trace_setuid"`
	TraceSocket      *ebpf.ProgramSpec `ebpf:"trace_socket"`
	TraceUnlinkat    *ebpf.ProgramSpec `ebpf:"trace_unlinkat"`
	TraceUnshare     *ebpf.ProgramSpec `ebpf:"trace_unshare"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	CapsetHeap    *ebpf.MapSpec `ebpf:"capset_heap"`
	DnsHeap       *ebpf.MapSpec `ebpf:"dns_heap"`
	Events        *ebpf.MapSpec `ebpf:"events"`
	FileHeap      *ebpf.MapSpec `ebpf:"file_heap"`
	MmapHeap      *ebpf.MapSpec `ebpf:"mmap_heap"`
	ModuleHeap    *ebpf.MapSpec `ebpf:"module_heap"`
	NamespaceHeap *ebpf.MapSpec `ebpf:"namespace_heap"`
	NetworkHeap   *ebpf.MapSpec `ebpf:"network_heap"`
	ProcessHeap   *ebpf.MapSpec `ebpf:"process_heap"`
	PtraceHeap    *ebpf.MapSpec `ebpf:"ptrace_heap"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	CapsetHeap    *ebpf.Map `ebpf:"capset_heap"`
	DnsHeap       *ebpf.Map `ebpf:"dns_heap"`
	Events        *ebpf.Map `ebpf:"events"`
	FileHeap      *ebpf.Map `ebpf:"file_heap"`
	MmapHeap      *ebpf.Map `ebpf:"mmap_heap"`
	ModuleHeap    *ebpf.Map `ebpf:"module_heap"`
	NamespaceHeap *ebpf.Map `ebpf:"namespace_heap"`
	NetworkHeap   *ebpf.Map `ebpf:"network_heap"`
	ProcessHeap   *ebpf.Map `ebpf:"process_heap"`
	PtraceHeap    *ebpf.Map `ebpf:"ptrace_heap"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.CapsetHeap,
		m.DnsHeap,
		m.Events,
		m.FileHeap,
		m.MmapHeap,
		m.ModuleHeap,
		m.NamespaceHeap,
		m.NetworkHeap,
		m.ProcessHeap,
		m.PtraceHeap,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	TraceBind        *ebpf.Program `ebpf:"trace_bind"`
	TraceCapset      *ebpf.Program `ebpf:"trace_capset"`
	TraceConnect     *ebpf.Program `ebpf:"trace_connect"`
	TraceExecve      *ebpf.Program `ebpf:"trace_execve"`
	TraceFchmodat    *ebpf.Program `ebpf:"trace_fchmodat"`
	TraceFinitModule *ebpf.Program `ebpf:"trace_finit_module"`
	TraceInitModule  *ebpf.Program `ebpf:"trace_init_module"`
	TraceMemfdCreate *ebpf.Program `ebpf:"trace_memfd_create"`
	TraceMmap        *ebpf.Program `ebpf:"trace_mmap"`
	TraceMprotect    *ebpf.Program `ebpf:"trace_mprotect"`
	TraceOpenat      *ebpf.Program `ebpf:"trace_openat"`
	TracePtrace      *ebpf.Program `ebpf:"trace_ptrace"`
	TraceRenameat2   *ebpf.Program `ebpf:"trace_renameat2"`
	TraceSendmsg     *ebpf.Program `ebpf:"trace_sendmsg"`
	TraceSendto      *ebpf.Program `ebpf:"trace_sendto"`
	TraceSetgid      *ebpf.Program `ebpf:"trace_setgid"`
	TraceSetns       *ebpf.Program `ebpf:"trace_setns"`
	TraceSetuid      *ebpf.Program `ebpf:"trace_setuid"`
	TraceSocket      *ebpf.Program `ebpf:"trace_socket"`
	TraceUnlinkat    *ebpf.Program `ebpf:"trace_unlinkat"`
	TraceUnshare     *ebpf.Program `ebpf:"trace_unshare"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.TraceBind,
		p.TraceCapset,
		p.TraceConnect,
		p.TraceExecve,
		p.TraceFchmodat,
		p.TraceFinitModule,
		p.TraceInitModule,
		p.TraceMemfdCreate,
		p.TraceMmap,
		p.TraceMprotect,
		p.TraceOpenat,
		p.TracePtrace,
		p.TraceRenameat2,
		p.TraceSendmsg,
		p.TraceSendto,
		p.TraceSetgid,
		p.TraceSetns,
		p.TraceSetuid,
		p.TraceSocket,
		p.TraceUnlinkat,
		p.TraceUnshare,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_arm64_bpfel.o
var _BpfBytes []byte
